### ISSUE TITLE
Not able to include Katex in my Android Studio Project

### ISSUE THREAD

**Issue by AmitBansal73** [judemanutd/KaTeXView#2]
ERROR: Failed to resolve: com.github.judemanutd:katexView

Below is my Module dependency list

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.android.support:support-v4:28.0.0'
    testImplementation 'junit:junit:4.12'
    implementation 'com.mcxiaoke.volley:library:1.0.19'
    implementation 'com.google.firebase:firebase-core:16.0.1'
    implementation 'com.github.bumptech.glide:glide:4.4.0'
    implementation 'com.google.android.gms:play-services-auth:15.0.1'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.github.judemanutd:katexView:1.0.1'
    implementation('com.paytm:pgplussdk:1.3.3') {
        transitive = true;
    }

    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

**Comment by judemanutd** [comment]
@AmitBansal73 thanks for pointing this out, there was an error with the naming it's `katexview` not `katexView`. I've fixed that in the readme ( 4273d6cd5df71739e56b637b9950f07e6ded863d ) , let me know if it works for you now.
