### ISSUE TITLE
cannot change the textColor.

### ISSUE THREAD

**Issue by Shani618** [judemanutd/KaTeXView#4]

**Comment by judemanutd** [comment]
Could you post a code snippet of what you have tried so far

**Comment by Shani618** [comment]
<com.judemanutd.katexview.KatexView
            android:id="@+id/testActivityTextViewQuestionBigMaths"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:gravity="center"
            android:scrollbars="vertical"
            android:textAlignment="center"
            app:textColor="@color/white" />

I have also tried "#fff"
and also
testActivityTextViewQuestionBigMaths.setTextColor(ContextCompat.getColor(getApplicationContext(),android.R.color.white));
and also

testActivityTextViewQuestionBigMaths.setTextColor(getResources().getColor(R.color.white));

**Comment by judemanutd** [comment]
@Shani618 thanks for the issue, pushed out a new version of the library with the bug fixed.
